image: Visual Studio 2017   # на этом VM-образе установлены все Visual Studio с 2008 по 2015

init:
    # секция инициализации, исполняется до клонирования проекта
    # скорее всего, строчка ниже необязательна (так должно быть по умолчанию),
    # вместе с тем, она присутствует в официальных примерах, так что пусть будет:
    - git config --global core.autocrlf input

clone_folder: C:\Users\Katya\source\repos\UPOLR2 # выбираем локальную директорию для клонирования c:\projects\my-prj
shallow_clone: true              # копируем только последний коммит, без истории (git clone --depth 1)

matrix:
    fast_finish: false           # не останавливаемся после возникновения ошибки в каком-то из заданий

platform:
    # будем гонять CI на amd64...
    - x64

configuration:
    # ... и в релизной конфигурации ...
    - Release
    
test_script:
  vstest.console .\x64\Release\Test_2.dll
