version: 1.0. {build}
 image: Visual Studio 2017
 configuration:
 - Release
 before_build:
   - ps: $Env:PLATFORM_TOOLSET="v141"
 build:
   project: UPOLR2.sln
   parallel: true
   verbosity: minimal
 test:
   assemblies:
     - '.\*\Test_2.dll'
 after_test:
   - vstest.console /logger:Appveyor Release\Test_2.dll
 artifacts:
 - path: Release\UPOLR2.exe
   name: Binary
 deploy: off 
